### ISSUE TITLE
Sorting: Files: List ist not sorted by filename

### ISSUE THREAD

**Issue by photasm** [xbmc/Kore#119]
If I browse files via "Files" the list is not sorted by filename instead by "display name".

In case of music, if I have e.g. two files "01 Zong.mp3" and "02 Song.mp3" the second one displays first, because its ID3-Tag says "Song".

The same happens with files of episodes of tv series.

It would be nice to have the option to sort these lists by filename. :)

thx

**Comment by sebastian-de** [comment]
I'm quite new to Kodi/Kore and I'm not a developer, but I'm trying to dig into this issue, as I mainly browse my music in files view.
Currently SORT_METHOD_LABEL ist set in [Files.Get.Directory](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/MediaFileListFragment.java#L323), maybe setting it to SORT_METHOD_FILE is enough.
I don't know yet if this also alters they way individual items are displayed or not. I'll try to set up a Dev-environment this week and test it.

**Comment by sebastian-de** [comment]
I was able to build the app and test different settings. All in all the way Kodi returns data for files/directories seems to be very inconsistent and therefore buggy, which causes this behavior. So this issue seems to be a dup of #65 an can be closed.

@SyncedSynapse can you tell me where the best place is to file a bug for that?
