### ISSUE TITLE
Report connection failures and their reasons

### ISSUE THREAD

**Issue by mvglasow** [xbmc/Kore#123]
When connection to the media center fails, the screen will just show "Connecting..." forever. I would like to see more precisely what is happening: is Kore just waiting for a response from the media center, or was the connection rejected due to bad credentials, or something else? The way it is, troubleshooting is hard, if not an outright matter of luck.

**Comment by SyncedSynapse** [comment]
I understand what you mean, but the thing is, there's no magic bullet for it. Consider:
- If it shows connecting, it is waiting for a response. If this is happening a lot to you, try going into the server's settings (in Kore), and unchecking the "Use TCP" option. It will use HTTP by default, which tends to either connect or not.
- Connection errors are better diagnosed on the server's settings (in Kore). Namely, bad credentials are identified and reported to the user.
- Apart from bad credentials, every other error is almost impossible to catch: The remote can't ever know if your firewall isn't correctly configured, if there's no route to Kodi because it's on a different network, etc. All these errors get reported as timeouts...

**Comment by mvglasow** [comment]
I understand everything will be impossible to catch. Especially, when it's a network issue (no route, blocked by firewall etc.), I don't expect Kore to figure that out. What I would expect Kore to do is to display a message when an error occurs on connection. In the above cases, a message stating "The connection timed out" would be sufficient for me.

I didn't find any diagnostic options in the server setting for a server that is already configured. I guess I need to explain myself better here: I had my media center set up but the next update reset my configuration so that my user name and password were no longer valid. Here I would assume Kore gets an unambiguous error code back from the server – and in that case, it should just display an appropriate message to the user.

And there are probably a few more connection errors that may happen: for instance, when TCP is used, the server may simply reply with a RST when there is no listener on that port (possible reasons: wrong port, wrong server or Kodi not running).

All of these may happen when connecting to a server that has previously been set up successfully. Therefore it's important to have this functionality not only in the setup activity but on every connection attempt.
