### ISSUE TITLE
[Feature Request] local playback, streaming media to android device

### ISSUE THREAD

**Issue by 115ek** [xbmc/Kore#125]
Are there any plans concerning that? I only found a download button in the current release.
Actually it should be possible to play (at least some music...) media on your android device without doing it in Kodi at the same time.
(I think yatse also has got such a feature.)
Please enlight me if I missed something in the settings of Kore. Maybe I'm only blind.
Best regards :)

**Comment by cryptobanana** [comment]
I'm working on this feature, as well as video. I have a partially working prototype for movies implemented in my own development branch: https://github.com/cryptobanana/Kore/tree/stream_video

I plan to finish this functionality for videos and audio in my free time over the holidays and submit a pull request soon.

**Comment by timofonic** [comment]
@cryptobanana 

Great!

I'm more interested in the audio-only option, to use headphones. Bluetooth is shitty!

**Comment by cryptobanana** [comment]
Hi, I have a proof-of-concept implementation (in progress) in my forked repository that allows a Kore remote to play TV and Videos locally on the remote device (as opposed to the kodi media center). The user interface is implemented by repurposing the "download" button in the TvShowEpisodeDetails and MovieDetails views. Audio would be a next step. I'm not yet ready to issue a pull request because it requires more iteration + cleanup, but feel free to try it yourself:

https://github.com/cryptobanana/Kore/tree/stream_video

**Comment by cryptobanana** [comment]
@SyncedSynapse: I'd like to kindly request some feedback on the video + audio streaming functionality I'm working on, as I'd like to ensure that it can be merged upstream: 

1) Choose a user interface for playing media (stream to device): Currently in my branch, I am re-purposing the "download" button in the TVShowEpisodeDetailsFragment and MovieDetailsFragment.java to stream a video and play it. Consequently download functionality no longer works. I would propose to address this by either: a) adding an additional button next to the download button specifically to initiate streaming local playback or b) modify the behavior of the floating action button so that upon pressing it, the user has the option to play on the kodi media center or to stream for local playback on the kore remote. I personally tend to prefer (b).

2) Reduce Code duplication: MovieDetailsFragment.java and TVShowEpisodeDetailsFragment.java duplicate a significant amount of code. I would propose to address this by moving as much of the duplicated code into higher classes as possible. Thoughts?

**Comment by SyncedSynapse** [comment]
@cryptobanana I won't have much time this week to review your branch, but i'll try to look at it at the weekend/next week.

Regarding your questions:
1. I also prefer b), though it comes at the expense of having one more tap for the most common case... Going this route, it should be a FAB that, when clicked "expands" to show the available options: play in Kodi and Play locally. Aditionally, if the video has a resume point it should show a Resume option (i'll do this in the future).

2. Sure, though it's hard for me to opine on the better option without knowing which code is duplicated and what it is doing. Just consider composition instead of inheritance also.

**Comment by poisdeux** [comment]
What's the status of this? Would be a great addition.

**Comment by SyncedSynapse** [comment]
This has been on my inbox since the beginning, but somehow i haven't been able to look at it... Sorry,

**Comment by jondo** [comment]
Can someone please post a screenshot of the GUI for this? I still only find the download button (in Kore 2.5.3).

**Comment by DieBauer** [comment]
> Can someone please post a screenshot of the GUI for this? I still only find the download button (in Kore 2.5.3).

The big plus at the bottom right!

**Comment by SyncedSynapse** [comment]
In the newer version, soon to hit the Play store, it is renamed to "Stream" and is in the middle of the screen.

**Comment by jondo** [comment]
Which screen should show this "big plus"? In the music > songs list, each song just has got a context menu listing "play", "add to playlist", and "download".

**Comment by jondo** [comment]
@SyncedSynapse  I have now got this "newer version", Kore v3.0.0. I cannot find this "Stream" button there! Can someone post a screenshot please?
