### ISSUE TITLE
Always 100% at volume, no 0-100%!

### ISSUE THREAD

**Issue by breakthecode** [xbmc/Kore#226]
I´m using OSMC and using Kore on my Nexus 6P for remote, and before that I was using a Nexus 6 with the same result.

Why is the volume only appears as 100%, even when you increase or decrease the volume and you hear it goes up or down, it is stuck at 100%.

Can fix a video of the problem to proof this if I need it.

**Comment by SyncedSynapse** [comment]
This doesn't look like an issue of Kore. Kore only sends the volume up/down command to Kodi, if the level isn't right on Kodi's UI it's an issue on Kodi's side (or OSMC build).

You probably get the same with a physical remote (or maybe not, because they use different protocols). I would suggest you to post this issue on the forum: http://forum.kodi.tv/forumdisplay.php?fid=52
