### ISSUE TITLE
settings menu: toggle buttons - strange behaviour

### ISSUE THREAD

**Issue by Michas1601** [xbmc/Kore#231]
When clicking on a toggle button in the settings menu all the buttons are set to a pseudo random pattern:
- when clicking the first, the last two are toggled
- when clicking the second, only the first one is toggled
etc.
also, on re-entering the settings menu the button states are changed.

**Comment by SyncedSynapse** [comment]
Can't reproduce this, and i strongly suspect it's an issue with your configuration, otherwise this would have been reported already.

The settings screen is as standard as it gets, it just uses Android's default mechanism for settings. There's very little that's handled in Kore's code, so this reinforces my suspicion that something's wrong with your device. Have you tried in another device?

**Comment by Michas1601** [comment]
You were right, on an other android phone the menu works, using the same kore version. (i am using a huawei with this disgusting EMUI.. slow as hell but never encountered real bugs)

anyways, downgrading to version 1.1, where it wasn't the official kodi remote app, (still in the store) fixed the problem.
thanks :)
