### ISSUE TITLE
Inefficient API is used

### ISSUE THREAD

**Issue by struggggle** [xbmc/Kore#357]
Dear developers,

I found an inefficient API, setImageResource(), is widely used in Kore.

For setImageResource(), Google says this:
https://developer.android.com/reference/android/widget/ImageView.html#setImageResource(int)
" This does Bitmap reading and decoding on the UI thread, which can cause a latency hiccup. If that's a concern, consider using setImageDrawable(android.graphics.drawable.Drawable) or setImageBitmap(android.graphics.Bitmap) and BitmapFactory instead. "

I noticed that in the following code, setImageResource() is used:

(1) org.xbmc.kore.utils.UIUtils.java    (line number: 226)
https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/utils/UIUtils.java

(2) org.xbmc.kore.ui.NowPlayingFragment.java   (line number: 760, 763, 766)
https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/sections/remote/NowPlayingFragment.java

(3) org.xbmc.kore.ui.RemoteFragment.java   (line number: 624, 625)
https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/sections/remote/RemoteFragment.java

(4) org.xbmc.kore.ui.NavigationDrawerFragment.java   (line number: 502, 517)
https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/generic/NavigationDrawerFragment.java

(5) org.xbmc.kore.ui.AlbumDetailsFragment.java   (line number: 392)
https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/sections/audio/AlbumDetailsFragment.java

The use of setImageResource() will affect Kore's performance, maybe we should replace it with setImageDrawable() or setImageBitmap(), and move Bitmap reading and decoding to a background thread.

Thanks.

**Comment by poisdeux** [comment]
Thank you for pointing this out. 
However, simply switching to setImageDrawable() or using a BitmapFactory will not solve the possible performance issues. It will need to be executed on a separate thread explicitly. So, the issue is not with using setImageResource() but running on the UI thread. If I'm correct, we use this only for small images and only a few. Thus, running this on the UI thread will unlikely cause any performance issues. I, therefore, do not think it is worth the effort to replace this.
