### ISSUE TITLE
Incorrect power options

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#43]
When connecting to my openelec machine I get the option "quit" while the option "reboot"  is missing. 
Quit isn't an option on openelec while reboot is. Not sure if the jsonrpc response for getting the options is correct or not.  iirc it should only return the options that the htpc actually supports

**Comment by SyncedSynapse** [comment]
Reboot should indeed be included. Didn't include it because i only tested it on a PC, and reboot isn't really helpful there.

As for quit, i didn't find anything in jsonrpc that indicates whether it is supported or makes sense. @Montellese Am i missing something? System.GetProperties lets you know whether the system can suspend/reboot/shutdown/hibernate, but not whether quit is appropriate.

**Comment by SyncedSynapse** [comment]
Reboot is in c6dfce29a4857e5bcc1df313381b4ae9c98de2c6.

Can't find anything in jsonrpc that specifies whether quit makes sense or not (there's only info about cansuspend, shutdown, restart), therefore i think this should be closed.
