### ISSUE TITLE
Directional keys don't work while in media playback 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/Kore#46]

**Comment by SyncedSynapse** [comment]
AFAIK jsonrpc doesn't have any method that does the 10s skipping thing. That is only available through EventServer, which Kore doesn't use.
There are valid alternatives (re/ffw, using the position tracker on now playing), so imo it's not justified implementing a EventServer interface just for this.

**Comment by MartijnKaijser** [comment]
imo we should be imitate the directional keys that you have using a regular keyboard/remote.
So is this only possible using eventserver during playback? 
@Montellese you know a way to do this with JSON-RPC?

**Comment by Montellese** [comment]
You have to use `Player.Seek` with `smallstepforward`, `bigstepforward`, `smallstepbackward` and `bigstepbackward`.

**Comment by SyncedSynapse** [comment]
@Montellese The thing is, afaict the remote can't reliably decide when to call `Input.Left/Right` or `Player.Seek`. Both these actions can be invoked by the same button in the remote D-Pad, and it can't decide when to call one or the other (media is playing isn't a sufficient condition because there might be some UI present, and in that case it should send `Input.Left` instead of `Player.Seek`).

The EventServer code probably includes some logic to deal with this (i haven't checked, guilty as charged), but it knows more about Kodi state than the remote.

In jsonrpc API there's `Input.Left/Right/Up/Down` and there's `Input.ExecuteAction` which can take "left"/etc - both behave the same way afaict. I don't know if it is possible, if it is simple or even if it makes sense, but isn't it possible to change `Input.ExecuteAction` to behave exactly as in the EventServer?

**Comment by Tolriq** [comment]
@MartijnKaijser what you ask is a 2 years old fight that I've lost :)

There's a problem for most of the Team about how action should be handled and how to offer them to remotes.

I should be able to find the threads to re open the discussion but the core was remote should not be able to call things that depends on keymaps that can be changed by users.

From an user point of view this means : I can configure Kodi to behave the way I like from my keyboard and physical remote but I have to do the same configuration on Android / iOS remote because it's not good the allow users to have the same behavior everywhere.

The team point of view was it's bad to allow a command to not have a predictable action, the user point of view is I have modified my keymap for a reason why don't you let me use my choice ?

I know for sure that users are right on this, but was never able to make someone on the team understand user point of view and need. Maybe this is another chance ?

**Comment by ThiefMaster** [comment]
**Please** bring back the functionality from the old XBMC remote! If using the same buttons is not an option, at least add a settings to re-map the fast-forward/fast-rewind buttons. I think they are inferior to the +/-10s seeks in all aspects - in what's probably the most common case, i.e. skipping the repetitive intro of a tv show, it's so easy to simply hit the seek-forward button a few times instead of playing with fast-forward (and being tortured by the terrible audio that comes with fast-forward playback) and then switching back to normal playback speed in the right moment.

**Comment by ThiefMaster** [comment]
> The team point of view was it's bad to allow a command to not have a predictable action, the user point of view is I have modified my keymap for a reason why don't you let me use my choice ?

I think the solution for this could be quite simple: Add another command "seek backwards or go left". That way there would be the unambiguous "seek backwards" and "go left" actions, but remotes that want to use the button for both could use the combined action.

**Comment by waltermartin** [comment]
I have to say that I think it is most definitely worth "implementing a EventServer interface just for this." There are NOT any valid alternatives. Other than pause/play and stop, these are the functions that I absolutely have to during playback. This app has a terrific interface, but without this functionality, I'll keep using Yatse instead. I have not seen any of the discussions that are mentioned, but this really seems like a case of developers making decisions about what is important to their users, rather than actually asking the users or doing any usability testing. A real shame, as this is otherwise a great app.

**Comment by waltermartin** [comment]
I have to say that I think it is most definitely worth "implementing a EventServer interface just for this." There are NOT any valid alternatives. Other than pause/play and stop, these are the functions that I absolutely have to during playback. This app has a terrific interface, but without this functionality, I'll keep using Yatse instead. I have not seen any of the discussions that are mentioned, but this really seems like a case of developers making decisions about what is important to their users, rather than actually asking the users or doing any usability testing. (Maybe I am wrong, but that is the impression I get.) A real shame, as this is otherwise a great app with a really nice design.

**Comment by titomontes** [comment]
I have the same approach here. This wonderful remote is completely useless during playback for me, and I keep switching from this to old remote while on playbak. The skip function is essential to me while watching TV series (and some movies).

PLEASE, implement this so needed feature!

**Comment by Mustack** [comment]
I'd like to also ask that this feature be considered. I'm unfamiliar with the API's so I won't suggest a solution but I'm sure a good solution can be found for this and I think it's a perfectly valid use-case.

**Comment by CGorni** [comment]
I would expect that, like me, those that use the skip functionality prefer it over fast forward and rewind. Could this be added as an option in the app settings that changes the function of the << and >> buttons to skip back and skip forward instead?

**Comment by titomontes** [comment]
It´s already been said that other approach has to be taken for skip to
work, and they seem to think that this is not worth it. Se we have to keep
using another remote. Really sad.

2015-06-06 0:02 GMT+02:00 CGorni <notifications@github.com>:

> I would expect that, like me, those that use the skip functionality prefer
> it over fast forward and rewind. Could this be added as an option in the
> app settings that changes the function of the << and >> buttons to skip
> back and skip forward instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/Kore/issues/46#issuecomment-109453210>.
>



-- 


*Saludos cordialesAugusto Montes"Solo hay 2 cosas infinitas: el universo y
la estupidez humana, y de la primera no estoy seguro"*
*Albert Einstein*

**Comment by waltermartin** [comment]
Yes, but hopefully the development team is not completely closed minded on the subject, and if enough users let them know how they feel, they will change their mind. If they really care they could always start a poll on the forum. Thankfully  Yatse works great, and I'll always take functionality over style.

**Comment by kokarn** [comment]
+1

**Comment by titomontes** [comment]
+1000

2015-06-07 14:07 GMT+02:00 Oskar Risberg <notifications@github.com>:

> +1
>
> On Sat, Jun 6, 2015 at 3:15 PM waltermartin <notifications@github.com>
> wrote:
>
>
> > Yes, but hopefully the development team is not completely closed minded
> on
> > the subject, and if enough users let them know how they feel, they will
> > change their mind. If they really care they could always start a poll on
> > the forum. Thankfully Yatse works great, and I'll always take
> functionality
> > over style.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/xbmc/Kore/issues/46#issuecomment-109577443>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/Kore/issues/46#issuecomment-109745249>.
>



-- 


*Saludos cordialesAugusto Montes"Solo hay 2 cosas infinitas: el universo y
la estupidez humana, y de la primera no estoy seguro"*
*Albert Einstein*

**Comment by antivirtel** [comment]
+1 ... I hope that it will at least the same as XBMC remote was, since it was working at least... how was these features implemented there? the hacky way?

**Comment by titomontes** [comment]
They have to implement EventServer, wich is a separate service from
JsonRPC, since it doesn´t support the 10s skipping. Anyway, it´s at the top
of the post...

2015-06-08 12:35 GMT+02:00 B. Roland <notifications@github.com>:

> +1 ... I hope that it will at least the same as XBMC remote was, since it
> was working at least... how was these features implemented there? the hacky
> way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/Kore/issues/46#issuecomment-109945182>.
>



-- 


*Saludos cordialesAugusto Montes"Solo hay 2 cosas infinitas: el universo y
la estupidez humana, y de la primera no estoy seguro"*
*Albert Einstein*

**Comment by titomontes** [comment]
BTW.

Why not open a poll?? I´m not sure if any user can do it, put perhaps we can convince a mod/dev to open one...

**Comment by antivirtel** [comment]
Ok, but why not put this extra feature to JsonRPC at the Kodi's site? So it can be accessible using just one "protocol".

**Comment by titomontes** [comment]
JsonRPC comes as is, it´s not easyly modifiable. It´s a structural change we´re talking about.

**Comment by antivirtel** [comment]
I've used RPC technology (RMI) via Java, and I just needed to define a new function on server's side, if I wanted some extra functionality. Is JsonRPC's source closed, or why is not modifiable?

**Comment by ThiefMaster** [comment]
https://github.com/xbmc/Kore/issues/46#issuecomment-85572364

**Comment by antivirtel** [comment]
I can't see any relevance with that comment, just excuses. I still don't get, why can't the team add more features/functions to JsonRPC?! If EventServer is not good, don't use it at all, but add this feature to that JsonRPC...

**Comment by MartijnKaijser** [comment]
@antivirtel they are pretty good excuses. If you alter the function of the buttons at Kodi side you alter the function of the remote as well. As such you will not have consistent for the remote if you switch Kodi installs.

Kodi is open source, if you think you can add the correct function to JSON-RPC feel free to do so. Why it hasn't been done yet is time and the proper implementation to make it consistent regardless of the Kodi install and advancedsettings used.

**Comment by Tolriq** [comment]
@MartijnKaijser there was proposal to improve JSON and add correct support for users needs, all were refused, so yes Kodi is open source, but not all features users want can get in even if someone code them. (And I did try a few times already)

I still have not seen any explanation or real discussion on why users from remote should not have access to configuration they have made.

The fact that input.right does trigger input.right and not a random function is logical and wanted.

But the refusal to have a way to trigger remote.right from JSON so that users have access to their keymaps they wanted and took time to configure is not logical at all.

This is the same for advanced settings, each time I asked on adding support for reading them from remotes the answer was no it's not wanted, so a user configure it's wanted articles for sorting, but remotes can't get the values he configured.

Anyway for this specific skip things, there's no possible workaround apart using EventServer, as there's no way to detect when to use right or skip (and it would need the user to reconfigure the skip to behave the way he loves as new progressive seek won't be loved by all users). (It's impossible to know if there's a window over the video or under like subtitles delay or OSD, hacks to detect commons window visible via labels may be done but it's not possible to cover all cases).

**Comment by SyncedSynapse** [comment]
I'm going to implement eventserver in the next version, so no need to argue further.

**Comment by Tolriq** [comment]
:( I was hopping official remote problems, becomes official and thing may change, but if even you give up and use hacks and this then it's a lost battle :(

**Comment by titomontes** [comment]
SyncedSynapse just said that he´s going to implement event server. I don´t get what battle was lost. 

Let´s just say thank you for your support, which by the way, is free.

Many thanks guys.

**Comment by Tolriq** [comment]
Well because you are not developer and do not understand the impact of what's going on in this thread ;)

You as Kore user have a little win, us remote developer have a big loose.

**Comment by titomontes** [comment]
For us users it´s a huge win. It´s perhaps one of the three functions most
used by everyone I know (including play and pause). As for the developers
point of view, yes, I can understand you are letting go so much.

2015-06-09 18:47 GMT+02:00 Tolriq <notifications@github.com>:

> Well because you are not developer and do not understand the impact of
> what's going on in this thread ;)
>
> You as Kore user have a little win, us remote developer have a big loose.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/Kore/issues/46#issuecomment-110428594>.
>



-- 


*Saludos cordialesAugusto Montes"Solo hay 2 cosas infinitas: el universo y
la estupidez humana, y de la primera no estoy seguro"*
*Albert Einstein*

**Comment by waltermartin** [comment]
I am a developer, but not for Kodi or using the particular technologies involved, so I don't know if there is a better way to do this. However, I am glad to read what SyncedSynapse wrote. This is more than just a little win for me as a Kore user.

**Comment by antivirtel** [comment]
@Tolriq
 > MartijnKaijser there was proposal to improve JSON and add correct support for users needs, all were refused

 > input.something

I'm not involved to the development of Kodi &  Kore (yet), but I'm a Java developer, and I think, that using input object is considered as a hacky solution, and that's why the head developers refuse to merge the pull requests.

My suggestion is, that those jump or seek functions bound to keyboard's arrows - already mentioned here - should be made public/available from JsonRPC... (ONLY IF something's playing AND that menu with the Stop, Play/Pause, FF... is not opened), it will use these functions, not the left/right functions!

I don't know what technology is used by the  EventServer, but the RPC is widely used, and I think one technique is far enough for remote controlling...

BTW, XBMC's official remote had that Swipe control mode, instead of these arrow up/down, left/right buttons - did those buttons need any back-end adjustments, or just UI and some time counter loops?

**Comment by Tolriq** [comment]
@antivirtel Well I tried to be involved numerous times (and have been some times) ;) And I'm developer of Yatse a way older remote than Kore, so I have a little more insight about how things works and what users want ;)

What you do miss is that the keyboard arrows are tied to keymaps and that's the main problem ;)
(Even if it should not but well no way to discuss). And no Input.something is not hacky it's opening the configuration users have made to remote, it should allows keyboard(xxx) and remote(xxx) to emulate keyboard and remotes from JSON, there's no valid reason to not open this and never was any real argument / discussions. (Specially when it's also refused to get access to those keymaps / advanced settings to try to reproduce without having user to do it's configuration again).

So it's a little more complicated than that, what the core team seems to want is a duplication of default keymaps code to handle this, or to hard code some actions when something is playing or tons of other things, but using the keymap that contains the configuration that the user wants.
(Keymap that change beetween Kodi release)

I'm a user I want left / right to skip 10 sec and up / down 30 sec I modify my keymap to do that, but when using a remote I need to find a remote that allows configuration of the buttons to reproduce the same behavior, but even if remotes could do that it's now impossible due to the lack of API to know if we should send UI commands or player commands.

And as you can see again in this thread, there's no way to discuss anything, no arguments, and when making PR you'll get as before a refusal without better proposal and have loose time for nothing.

So until the Team understand the need or agree to discuss on what should be done, EventServer that use the configuration of the user is the only possible solution and that's a shame.

**Comment by antivirtel** [comment]
Yes, I've already been understood this problem, but I still have doubts, because it seems, that you all not really get my question and/or suggestion.
That's why I'll investigate this JsonRPC, if I'd have time, and will write concrete suggestion, instead of the logical reasoning!
(don't expect this, till the end of the week!)

**Comment by pavlos256** [comment]
This is a must-have!

Any news?

**Comment by onetigr** [comment]
it's so queer it works for Mac but doesn't work for PC

**Comment by sokarsg-1** [comment]
Kore v2.3.2 + Kodi 14.4 Git:20170913-5cc491e on Raspbian Stretch  and directional keys don't work during playback. Any ideas how to check what is causing a problem, it was update for both Kore and Kodi in last mounth?

**Comment by SyncedSynapse** [comment]
@sokarsg-1 Anything changed in your network that might be blocking port 9777 (or whatever you've set up for EventServer)?

**Comment by sokarsg-1** [comment]
Its look like that, but only think i changed is samba config.

All my open ports:
PORT     STATE SERVICE     VERSION
22/tcp   open  ssh         (protocol 2.0)
139/tcp  open  netbios-ssn Samba smbd 3.X - 4.X (workgroup: CELL)
445/tcp  open  netbios-ssn Samba smbd 4.5.8-Debian (workgroup: CELL)
1054/tcp open  upnp        Platinum UPnP 1.0.5.13 (UPnP/1.0 DLNADOC/1.50)
5900/tcp open  vnc         RealVNC Enterprise 5.3 or later (protocol 5.0)
8080/tcp open  http        XBMC Web Media Manager
9090/tcp open  jsonrpc     XBMC JSON-RPC 2.0

**Comment by SyncedSynapse** [comment]
Try opening pot 9777
