### ISSUE TITLE
[Feature request] play randomly all music library

### ISSUE THREAD

**Issue by Benance** [xbmc/Kore#478]
Hello,
Before Kore V2.3.0, when you wanted to play just one music track, All the music library was played randomly instead.
Despite it was considered as a "bug" (see issue #362 ), this behaviour was (for me) a very interesting fonctionnality:
It was a fast way to play randomly all my music library.
Now, the bug is fixed and I havn't found any solution to randomly play my music library again with Kore.
Is  there a way to do this?
Thanks a lot for your answers.
Regards.

**Comment by Geodeve** [comment]
Did you try this?
[http://patch-recepteur.blogspot.com/2017/11/kore-official-remote-for-kodi-for.html]
(http://patch-recepteur.blogspot.com/2017/11/kore-official-remote-for-kodi-for.html)

**Comment by Benance** [comment]
Nobody's in the developpement team is interessed about such a fonctionnality?
Am I the only kore user who uses Kodi in a headless way to play music on my hifi?

**Comment by topas-rec** [comment]
>Am I the only kore user who uses Kodi in a headless way to play music on my hifi?

I do this, too and i also would like to add all songs to the queue, but the answer is the same you get everywhere: this is open source. If no one is interested and can do it it won't be done. Find and pay someone for doing it also helps of course. 

Another idea is to find an alternate solution. Two possibilities are already there:

1. Start your music from kodi (not the remote kore) by playing all tracks (play one track from the tracks section)
2. Use something else rather than kodi: [Jellyfin](jellyfin.org/)  for example. The good thing: it offers a kodi plugin, so you can keep that awesome project running,  the learning thing: you need to install the jellyfin server. But if that is done you get a lot extra features (synchronised playback, easier selection of the playback device and synchronised library across devices - just some examples).

**Comment by adrien-github** [comment]
Hi,
I am also interested to have Party Mode in Kore.

By the way the default web interface, Chorus, is able to launch the Party Mode. It can be a workaround for the users of Party Mode 

Kind regards

**Comment by SyncedSynapse** [comment]
Party mode can now be launched from the remote screen, though only *after* music has started.
