### ISSUE TITLE
[BUG or Feature Request] Arrows buttons not working as expected while playing a video

### ISSUE THREAD

**Issue by Smeulf** [xbmc/Kore#510]
Hello,

While playing a video, I would have expect the arrows to work the same as with a physical remote using CEC : up and down to change the chapter, and left and right for skipsteps.

With Kore V2.3.3 this is not working. I can't remember if it was working before, I'm sorry.

My Kodi host is a LibreElec 8.2.3 (Kodi 17.6), and my phone is running Android 7.0

Can someone confirm this is a bug? Or can you add it as a feature request?

Should you need any more information, please let me know.

Thanks.

Smeulf.

**Comment by SyncedSynapse** [comment]
It works as you describe, as long as you have EventServer enabled on Kodi, and Kore can communicate through it (need to be correctly configured on Kore and have access through any firewall to port 9777).

I'm going to close this because i believe it isn't an issue. If you find that changing the config doesn't fix it, please reopen it, but i use this everytime.

**Comment by Smeulf** [comment]
Thanks SyncedSynapse,

It's indeed an EventServer config issue. Sounds like it's a recurrent problem on my side :/

I could enable the event server after multiple tries. The RPi host is on the same LAN as my kore remote, so no firewall issues here, for now I can't understand what's happening.

"Funny" part : now I can use the arrows as expected, but the time slidebar and current time of the video is not updated, unless I pause/unpause the video, or force Kore to reload the values by displaying an another app and go back to kore, or switch the screen off then on. And I have the same issue on a test Windows host with Kodi 17.6, so it's not RPi/LibreELEC related.

I tried with an another remote (won't say the name, I do prefer Kore so much ^^) and I don't have the same problem, but I don't know if they use EventServer for this, or at all.

Can you confirm this part is also working on your side ?

Thanks for your always good support!

Smeulf.

**Comment by SyncedSynapse** [comment]
Yes, that can happen. Open a new issue with that description if you'd like to track it.

It only happens if you connect through TCP (so for now you can change it to HTTP if that bothers you). Kore isn't very "aggressive" in maintaining state, so it keeps the calls to Kodi at a minimum, and relies on Kodi informing it that something has changed (such as a pause/play speed/etc). It seems that Kodi doesn't trigger that for a skip so Kore counter can get out of sync. We can call into Kodi periodically to make sure it gets synced.
