### ISSUE TITLE
Feature request: long-press menu to mark items as watched

### ISSUE THREAD

**Issue by benedetto** [xbmc/Kore#53]
I'm currently adding a lot of old, already watched TV series to my Kodi database which are showing up as unwatched in the first place and are to be marked as watched then.

At the moment I have two ways to mark them as seen: in Kore I can open the episode view and tick the "mark as watched" button and go back to the episodes list and repeat that for every single episode or I can use the control arrow key to navigate through the database on the screen and mark there episodes or whole seasons/series as watched. Both ways are quite annoying, the former because it's a lot of going back and forth between different lists and views, the latter because working on the screen with the mobile phone as remote control requires constant switching between looking on the screen and on the phone.

To make like easier it would be great to have a long-press context menu to mark an item as watched without having to enter the info page of every single item or having to navigate through the screen menus.

**Comment by MartijnKaijser** [comment]
And after some one else comes along requesting longpress to refresh the complete tvshow. Where's the line to draw? I don't see common usage value in adding this.

**Comment by SyncedSynapse** [comment]
Well, what you ask is not possible because Kore doesn't know what episode/tvshow/movies/etc is selected on Kodi's side.
Even if it was possible, i also don't think this is something that should be done. It's not a common action, so it shouldn't be pegged to one of the remote buttons.

Sorry, you'll have to do it the way you've done it till now.
