### ISSUE TITLE
File browser shows wrong directory names

### ISSUE THREAD

**Issue by rigid** [xbmc/Kore#65]
It seems as if some directories are named like the scraper result of a file inside that directory.

I have this directory structure:
* 60s
 * foo.mp3
* 70s
 * bar.mp3
* 80s
 * baz.mp3
* 90s

Kore displays the directory like this:

60s
Bar - The Bar Song
80s
90s

**Comment by DanhKE6D** [comment]
@SyncedSynapse It seems to me that if itemFile.filetype is a directory, itemFile.label should be used as the title for the directory. I don't have any song/video in my database so I did not see this behavior, but if someone already has lots of songs/videos in the database, the json rpc response may be different. In the code for newInstanceFromItemFile, title was changed to something different than itemFile.label before it was FileLocation object was instantiated.

**Comment by SyncedSynapse** [comment]
This is not an issue as far as i'm concerned. If the scrapper has "indexed" those files, the info obtained by it is shown, instead of the simple file name. More useful imo.

**Comment by rigid** [comment]
So what's the point of the "File" feature then and why not use the library in the first place? it can be argued if a "file browser" should display real filenames or metadata;
but naming the directory using scraper info from a file _inside_ this directory is wrong.

**Comment by SyncedSynapse** [comment]
It's a conscious decision to shown all the metadata that is returned by Kodi.

Regarding the naming of the directory: Kore is only showing what is returned by Kodi. It is not digging into the directory to check if there is only one file and naming it accordingly. That issue is probably in the scrapper. If you go to the music->files section in Kodi, how does that directory appear?

**Comment by rigid** [comment]
Then it's the same behaviour as in "Music", just using the real directory structure (which is incorrectly named by now).

Music -> Files shows only real filenames. In my example:

60s
70s
80s
90s

no metadata neither on directories nor on files. Even the file suffix is shown. (btw. i'm using kodi nightlies, please tell me if you need more info.)

**Comment by SyncedSynapse** [comment]
In Kodi i also see the metadata when navigating through files. We probably have some different setting.

Anyway, Kore is showing the metadata for each dir/file and i think that's useful. If the metadata shown/obtained by the scrapper is incorrect, that should be dealt with on the scrapper.

**Comment by rigid** [comment]
i wonder how "metadata for each directory" could work. There is not even a remote way any scraper could name the directory any better than I did already.

and still: no, Kore is not showing metadata for each directory but instead for some random file inside it.

**Comment by SyncedSynapse** [comment]
As i've said before: Kore is displaying the metadata returned by Kodi for files/directories. If there are issues with the metadata on Kodi, it's not an issue of the remote.

If this is a request to not show the metadata, i won't do that.

**Comment by alecz20** [comment]
This one thing that I really liked about the old XBMC remote: the File Browser was a File Browser.

**Comment by rigid** [comment]
:+1:
Also long filenames are handled better there. I quit using kore in favour of XBMC remote.
I hope, functions besides the remote will be usable in the future (or me having the time to fork) :)

**Comment by 0rkaM** [comment]
This bug is still open on Kodi 16.1 and Kore 2.1.0;
For example I have a shared NAS that KODI on a Dell Duo Convertible 1090 laptop running Windows 7 access for video media, so the hard-drives cluster uses samba and is showing as a networked/shared drive named Media.
Inside Media share there are three folders: Audio, Video, Photo;
Inside Video there are some folder with some video and some other folders are video under sub-folders.
In the File Browser in Kore each folder without sub-folders is named as the meta-data of the first video file only; this makes it impossible to select or even see the other files, since clicking on that entry will actually play the video and not descent the directory and see the other files.
n Kore file browser

**Comment by alecz20** [comment]
@0rkaM 
see: https://github.com/xbmc/Kore/issues/65#issuecomment-93504900
This issue is a **WontFix**.
They do not want to show the File Structure in the File Browser. It is their project and it's open source, so as @rigid says, we would need to fork it to change the behavior.

**Comment by 0rkaM** [comment]
@alecz20 I saw [#65 (comment)](https://github.com/xbmc/Kore/issues/65#issuecomment-93504900), but it seems to me that he says "_If this is a request to not show the metadata, i won't do that._" even if it is kind of silly not to show the actual file/directory structure, since it is an actual file browser, but at least it should behave like the file browser in Kodi: and be able to descent a directory and see either the the Metadata, or the files if the scrapper did not find a match.
I am fine and OK with either of the two, or both, but the problem is that you cannot descent the directory and it will only show one media file metadata info, instead of the real folder-name, when instead it contains multiple media files.
And that is not what kodi passes, since it works fine on kodi file browser... that is a code problem... it is getting the metadata only for one file in each directory and it places in view that single information instead of all of the files informations, or at least the folder information to descent to.
Also that is against the way [Kodi folder convention](http://kodi.wiki/view/Video_management) works: you can have both multiple folders with one media file per folder, and also you can have folders with multiple media files in it and both are being scrapped correctly in Kodi and added to the library database and visible all around including the file browser.
In Kore you cannot, and anybody can see that the functionality is deficient: you do not see the multiple media files that are in the folder, nor their real-name info, nor their metadata info; you only see one media files metadata information even if the folder contains multiple ones... so what is the point of using it???
So to conclude, my point is not really about what information to show in the file browser, metadata, or actual file/folder names, but to show something at all, especially when there are directories with multiple media files, basically all of them except rips.
If anything, upstream from Kodi should be the base standard, from which you can deviate to add functionality, but not subtract, or break: so for **each media file** it should be medata info if it exists, but revert to file-names and folder-names if it does not... the key here is **EACH MEDIA FILE**.

**Comment by rigid** [comment]
@0rkaM thanks for expressing what I failed to express.

**Comment by sebastian-de** [comment]
As seen by issue #119 this behavior irritates a lot of people (including me). I'd like to see a usable file-browser for Kore, but right now it seems to be broken.
I tested using Kore v2.1.0 and fresh installs of Kodi v17.0-beta5 and v16.1, both with default settings. Every time the result was an unusable file-browser in Kore. The files on the Kodi installations themselves get listed as they should.
I think this situation is quite unsatisfactory - does anybody have an idea how this could be fixed?

**Comment by jondo** [comment]
I guess that the next step would be for someone to create and maintain a patch. Then, a Kore fork containing this patch could be released.

**Comment by sebastian-de** [comment]
In the meantime I asked in the official Kodi forum if this is something that could be fixed in Kodi itself. The short answer was "no", see http://forum.kodi.tv/showthread.php?tid=299904&pid=2485410#pid2485410

**Comment by sebastian-de** [comment]
I created a patch that shows the filename/foldername as details of the file items. This might be a compromise.
https://github.com/sebastian-de/Kore/commit/690cc562befcc508f93d18b8b8ef8c2d550424b7

I attached some screenshots below
![screenshot_20170422-221448](https://cloud.githubusercontent.com/assets/7430495/25307914/10063d74-27aa-11e7-98db-28d4b6e5c768.png)
![screenshot_20170422-221509](https://cloud.githubusercontent.com/assets/7430495/25307910/0a426a7a-27aa-11e7-9cf3-3c26a2520996.png)
![screenshot_20170422-221553](https://cloud.githubusercontent.com/assets/7430495/25307908/011891a4-27aa-11e7-8674-ba8fea25498f.png)

What do you think?
Also, for full functionality, theres still #124 , I have to figure out, how this could work
