### ISSUE TITLE
[bug] TCP/EventServer checkboxes not saved

### ISSUE THREAD

**Issue by Crashillo** [xbmc/Kore#705]
Once you setup a remote, and you activate some advanced settings, back again and such settings are not active.

Test it both Kore 2.4.7 and 2.5.0. Kodi is LibreELEC.

**Comment by SyncedSynapse** [comment]
Strictly, it isn't a bug.

When you select the TCP/Event server options and save it, Kore tries to contact Kodi to see if it can use those, and if it cannot, it automatically disables those options, as they are not strictly needed (only HTTP is mandatory).

Your network is probably blocking ports 8080 and/or 9777 somewhere, so that TCP and Event server aren't usable on Kore.

You could argue that Kore should warn about that, instead of automatically deselecting them, but this was a choice made in order to simplify the process for users that don't care about these technical issues, and i think it was the right choice, so i'm closing this for now. 
If i misunderstood this, and your issue has nothing to do with this, reopen it.

**Comment by Crashillo** [comment]
If I understood you, you're right, as the following output should say `LISTEN` for the udp port as well, shouldn't it, @SyncedSynapse?

```
LibreELEC:~ # netstat -putan | grep -E "8080|9777"
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      362/kodi.bin
tcp        0      0 192.168.1.12:8080       192.168.1.11:53214      ESTABLISHED 362/kodi.bin
tcp        0      0 :::8080                 :::*                    LISTEN      362/kodi.bin
udp        0      0 127.0.0.1:9777          0.0.0.0:*                           362/kodi.bin
```

**Comment by SyncedSynapse** [comment]
Looking at that, it seems Kore/Kodi are able to talk through TCP (port 8080), though not through 9777, so Kore doesn't save that.

Closing this, as it's working as designed (though you might disagree, obviously)

**Comment by jfly** [comment]
For the record, I do find the current behavior pretty confusing. If I manually select "Use EventServer", I would expect to get a clear error message if Kore cannot connect to my event server.

> You could argue that Kore should warn about that, instead of automatically deselecting them, but this was a choice made in order to simplify the process for users that don't care about these technical issues, and i think it was the right choice, so i'm closing this for now.

I agree it's find to not distract users who aren't expressing a preference, but for more technical users who are explicitly trying to turn on EventServer, I think that would be a sign that we should tell the user what's going on.
